"""
hf_utils.py

Core Hugging Face utility functions for the Bible RAG chatbot.
Provides reusable functions to check model availability and 
query hosted Hugging Face models via the inference API.
"""

import os, requests, sys
from dotenv import load_dotenv
from huggingface_hub import model_info

# Load API key from .env file
load_dotenv()
HF_API_KEY = os.getenv("HUGGINGFACE_API_KEY") 

# Common API URL and headers
api_url = f"https://router.huggingface.co/v1/chat/completions"
headers = {"Authorization": f"Bearer {HF_API_KEY}"}

# System prompt
SYSTEM_PROMPT = """
You are a Bible study assistant.

You must answer questions using ONLY the provided Scripture passages.
Do NOT use outside knowledge, assumptions, or additional verses.

Rules:
- Quote Scripture verbatim when referencing verses.
- Do not invent, paraphrase, or modify biblical text.
- If the provided passages do not fully answer the question, say so clearly.
- Do not introduce theological interpretations that are not directly supported by the text.
- Maintain a respectful, neutral, and explanatory tone.

Always format your response exactly as follows:

Answer:
<Direct answer based strictly on the provided passages>

Verse reference:
<List the relevant book, chapter, and verse ranges>

Explanation:
<A clear explanation of how the passages support the answer>
""".strip()

def check_model_inference_status(model_name: str) -> bool:
    """
    Check if a Hugging Face model is available for inference.
    
    Parameters:
        model_name (str): The model ID (e.g., 'google/gemma-2-2b-it')
    
    Returns:
        bool: True if model is available for inference, False otherwise
    """
    try:
        info = model_info(model_name, expand="inference")
        # If inference is "warm", the model is available
        return info.inference == "warm"
    except Exception as e:
        print(f"Error checking model {model_name}: {e}")
        return False

def query_hf(model_name: str, prompt: str, max_tokens: int = 512, temperature: float = 0.0) -> str:
    """
    Send a prompt to a Hugging Face model via the inference API and return the generated text.

    Parameters:
        model_name (str): The Hugging Face model ID to query (e.g., 'mistralai/Mistral-7B-v0.2').
        prompt (str): The text prompt to provide to the model.
        max_tokens (int, optional): Maximum number of new tokens to generate. Default is 512.

    Raises:
        RuntimeError: If the inference request fails or returns a non-200 HTTP status code.

    Returns:
        str: The text generated by the model in response to the prompt.
    """
    
    payload = {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt}
        ],
        "model": model_name,
        "max_tokens": max_tokens,
        "temperature": temperature
    }
    response = requests.post(api_url, headers=headers, json=payload)
    if response.status_code != 200:
        raise RuntimeError(f"HF inference failed: {response.status_code} {response.text}")

    return response.json()["choices"][0]["message"]["content"].strip()