"""
hf_utils.py

Core Hugging Face utility functions for the Bible RAG chatbot.
Provides reusable functions to check model availability and 
query hosted Hugging Face models via the inference API.
"""

import os, requests, sys
from dotenv import load_dotenv
from huggingface_hub import model_info

# Load API key from .env file
load_dotenv()
HF_API_KEY = os.getenv("HUGGINGFACE_API_KEY") 

# Common API URL and headers
api_url = f"https://router.huggingface.co/v1/chat/completions"
headers = {"Authorization": f"Bearer {HF_API_KEY}"}

# System prompt
SYSTEM_PROMPT = """
You are a Bible question-answering assistant.

STRICT RULES:
- Use ONLY the Scripture passages explicitly provided in the prompt.
- Do NOT invent, infer, reconstruct, or recall any verse not listed.
- Do NOT describe a sequence, timeline, or process unless ALL steps of that sequence are explicitly present in the provided passages.
- Do NOT merge ideas across passages unless the passages themselves explicitly connect them.
- Do NOT assume continuity from book structure (e.g., Genesis 1 progression).

- Do NOT reveal internal reasoning, chain-of-thought, or hidden analysis.
- Do NOT add outside knowledge, commentary, or interpretation.

ALLOWED:
- Quote Scripture passages exactly as provided.
- Clarify archaic words or expressions in parentheses if needed (e.g., charity → love), without changing meaning.
- Restate Scripture in simpler language ONLY when directly grounded in quoted verses.

If the provided passages do not fully answer the question, state this clearly and stop.
Do NOT mention or allude to missing commonly known verses.
If your response does not exactly follow the OUTPUT FORMAT, it is considered incorrect.
Always remain literal, text-faithful, and bounded by the given passages.
""".strip()

def check_model_inference_status(model_name: str) -> bool:
    """
    Check if a Hugging Face model is available for inference.
    
    Parameters:
        model_name (str): The model ID (e.g., 'google/gemma-2-2b-it')
    
    Returns:
        bool: True if model is available for inference, False otherwise
    """
    try:
        info = model_info(model_name, expand="inference")
        # If inference is "warm", the model is available
        return info.inference == "warm"
    except Exception as e:
        print(f"Error checking model {model_name}: {e}")
        return False

def query_hf(model_name: str, prompt: str, max_tokens: int = 512, temperature: float = 0.0, verbose: bool = False) -> str:
    """
    Send a prompt to a Hugging Face model via the inference API and return the generated text.

    Parameters:
        model_name (str): The Hugging Face model ID to query (e.g., 'mistralai/Mistral-7B-v0.2').
        prompt (str): The text prompt to provide to the model.
        max_tokens (int, optional): Maximum number of new tokens to generate. Default is 512.
        verbose (bool): If True, print debug info.

    Raises:
        RuntimeError: If the inference request fails or returns a non-200 HTTP status code.

    Returns:
        str: The text generated by the model in response to the prompt.
    """

    if verbose:
        print("Prompting LLM...")
        print(f"Model in use: {model_name}")
    
    payload = {
        "messages": [
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": prompt}
        ],
        "model": model_name,
        "max_tokens": max_tokens,
        "temperature": temperature
    }
    response = requests.post(api_url, headers=headers, json=payload)
    if response.status_code != 200:
        raise RuntimeError(f"HF inference failed: {response.status_code} {response.text}")
    
    if verbose:
        print(f"LLM inference completed.")

    return response.json()["choices"][0]["message"]["content"]